export type RideStatus = 'pending' | 'active' | 'completed' | 'cancelled';

export type UserRide = {
  id: string;
  driverName: string;
  driverPhoneNumber?: string;
  pickup: string;
  dropoff: string;
  requestedAt: string;
  status: RideStatus;
  cancelledBy?: 'user' | 'driver';
  vehicle: string;
  rating?: number;
  userReview?: {
    rating: number;
    comment?: string;
  };
  driverReview?: {
    rating: number;
    comment?: string;
  };
};

export const mockUserRides: UserRide[] = [
  {
    id: 'r1',
    driverName: 'Mike Johnson',
    driverPhoneNumber: '+1234567890',
    pickup: 'Downtown LA, 5th Street',
    dropoff: 'West LA Auto Shop',
    requestedAt: '2026-04-30T14:30:00',
    status: 'active',
    vehicle: 'Honda Civic 2019',
  },
  {
    id: 'r2',
    driverName: 'Sarah Williams',
    driverPhoneNumber: '+1234567890',
    pickup: 'Santa Monica Blvd',
    dropoff: 'Beverly Hills Repair',
    requestedAt: '2026-04-15T14:00:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
    rating: 5,
    userReview: {
      rating: 5,
      comment: 'Excellent service! Very professional and quick.',
    },
    driverReview: {
      rating: 5,
      comment: 'Great communication from the rider.',
    },
  },
  {
    id: 'r3',
    driverName: 'David Chen',
    driverPhoneNumber: '+1234567890',
    pickup: 'Hollywood Hills',
    dropoff: 'Downtown Service Center',
    requestedAt: '2026-04-12T08:30:00',
    status: 'completed',
    vehicle: 'Nissan X-Trail',
  },
  {
    id: 'r4',
    driverName: 'Kevin Singh',
    driverPhoneNumber: '+1234567890',
    pickup: 'Long Beach',
    dropoff: 'LAX Service Lane',
    requestedAt: '2026-04-28T10:15:00',
    status: 'pending',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r5',
    driverName: 'Jane Doe',
    driverPhoneNumber: '+1234567890',
    pickup: 'Venice Beach',
    dropoff: 'Marina Del Rey Shop',
    requestedAt: '2026-04-13T11:30:00',
    status: 'cancelled',
    cancelledBy: 'driver',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r6',
    driverName: 'Robert Martinez',
    driverPhoneNumber: '+1234567890',
    pickup: 'Culver City',
    dropoff: 'LAX Auto Center',
    requestedAt: '2026-04-11T10:30:00',
    status: 'cancelled',
    cancelledBy: 'user',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r7',
    driverName: 'John Doe',
    driverPhoneNumber: '+1234567890',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r8',
    driverName: 'John Doe',
    driverPhoneNumber: '+1234567890',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r9',
    driverName: 'John Doe',
    driverPhoneNumber: '+1234567890',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r10',
    driverName: 'John Doe',
    driverPhoneNumber: '+1234567890',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r11',
    driverName: 'John Doe',
    driverPhoneNumber: '+1234567890',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r12',
    driverName: 'John Doe',
    driverPhoneNumber: '+1234567890',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r13',
    driverName: 'John Doe',
    driverPhoneNumber: '+1234567890',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r14',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r15',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r16',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r17',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r18',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r19',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r20',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r21',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r22',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r23',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r24',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r25',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r26',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r27',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r28',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r29',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r30',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r31',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r32',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r33',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r34',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r35',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r36',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r37',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r38',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r39',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r40',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r41',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r42',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r43',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r44',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r45',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r46',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r47',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r48',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
  {
    id: 'r49',
    driverName: 'John Doe',
    pickup: 'San Fernando',
    dropoff: 'Point Fortin',
    requestedAt: '2026-04-10T08:30:00',
    status: 'completed',
    vehicle: 'Toyota Corolla',
  },
];

export function getUserRideById(id: string): UserRide | undefined {
  return mockUserRides.find((r) => r.id === id);
}
